### ISSUE TITLE
TSNE visualization

### ISSUE THREAD

**Issue by yanhan111** [val-iisc/RMLVQA#1]
Thanks for your excellent work! I'm a little confused about how to get the 2-D embedding features of the answers, i.e., the results in Figure 3 in the original paper. Would you mind sharing the code for the visualization part?

**Comment by hc0527** [comment]
Hi classmate, have you solved the visualisation part yet? I'm plagued by this problem as well.

**Comment by hc0527** [comment]
> Thanks for your excellent work! I'm a little confused about how to get the 2-D embedding features of the answers, i.e., the results in Figure 3 in the original paper. Would you mind sharing the code for the visualization part?

Hi classmate, have you solved the visualisation part yet? I'm plagued by this problem as well.

**Comment by abhipsabasu** [comment]
Hi all, we will upload the code for the TSNE-evaluation very shortly. To visualize the plots, we generally take around 100 embeddings of different question types and plot it after dimension reduction to 2d. We will share the official code for this shortly.

**Comment by hc0527** [comment]
> Hi all, we will upload the code for the TSNE-evaluation very shortly. To visualize the plots, we generally take around 100 embeddings of different question types and plot it after dimension reduction to 2d. We will share the official code for this shortly.

Hello dear author, can you please upload the code for the visualisation in the next couple of days, your help is much appreciated!
